import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import Card from '../components/card';
import styles from '../styles/Home.module.css';

import coffeeStoresData from '../components/data/coffee-stores.json';

export async function getStaticProps(context) {
  console.log('hi getStaticProps');
  return {
    props: { coffeeStores: coffeeStoresData },
  };
}

export default function Home(props) {
  console.log('props', props);
  const handleOnBannerBtnClick = () => console.log('hi banner button');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStoresData.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffeeStore/${coffeeStore.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
        <div className={styles.heroImage}>
          <Image
            src='/static/hero-image.png'
            alt='lady with coffee mug'
            width={700}
            height={400}
          />
        </div>
      </main>
    </div>
  );
}
